[package]
name = "mcmc-bot"
version = "0.1.0"
authors = ["ace"]
edition = "2021"

[dependencies]
serenity = { version = "0.12", features = [ "full" ] }
tokio = { version = "1.21.2", features = [ "macros", "rt-multi-thread" ] }
markov = "1.1.0"
